-- Gold transforms are now handled by PyIceberg via scripts/run_gold.py.
-- DuckDB is used for compute (SQL transforms on Arrow tables) only.
-- Iceberg writes go through PyIceberg with proper partition specs and catalog management.
